-- Wave's pre-Flyway schema. Existing installations are baselined at version 1,
-- while clean installations execute this migration before subsequent upgrades.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_verified BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    username VARCHAR(30) NOT NULL UNIQUE,
    bio VARCHAR(300),
    avatar VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('USER', 'ADMIN')),
    status VARCHAR(255)
);

CREATE TABLE workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    updated_at TIMESTAMP(6) NOT NULL,
    description VARCHAR(1000),
    name VARCHAR(255) NOT NULL
);

CREATE TABLE workspace_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    joined_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    role VARCHAR(255) NOT NULL CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER')),
    CONSTRAINT uq_workspace_member UNIQUE (workspace_id, user_id)
);

CREATE TABLE channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_private BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    description VARCHAR(500),
    name VARCHAR(255) NOT NULL
);

CREATE TABLE channel_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL REFERENCES channels(id),
    joined_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    CONSTRAINT uq_channel_member UNIQUE (channel_id, user_id)
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deleted BOOLEAN NOT NULL,
    edited BOOLEAN NOT NULL,
    channel_id BIGINT NOT NULL REFERENCES channels(id),
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    edited_at TIMESTAMP(6),
    parent_message_id BIGINT REFERENCES messages(id),
    sender_id BIGINT NOT NULL REFERENCES users(id),
    updated_at TIMESTAMP(6) NOT NULL,
    content VARCHAR(4000) NOT NULL
);

CREATE TABLE reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    message_id BIGINT NOT NULL REFERENCES messages(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    emoji VARCHAR(20) NOT NULL,
    CONSTRAINT uq_message_reaction UNIQUE (message_id, user_id, emoji)
);

CREATE TABLE pinned_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL UNIQUE REFERENCES messages(id),
    pinned_at TIMESTAMP(6) NOT NULL,
    pinned_by BIGINT NOT NULL REFERENCES users(id)
);

CREATE TABLE message_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES messages(id),
    read_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    CONSTRAINT uq_message_read UNIQUE (message_id, user_id)
);

CREATE TABLE file_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_size BIGINT NOT NULL,
    message_id BIGINT NOT NULL REFERENCES messages(id),
    uploaded_at TIMESTAMP(6) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    storage_path VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL
);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    last_message_at TIMESTAMP(6),
    user_one_id BIGINT NOT NULL REFERENCES users(id),
    user_two_id BIGINT NOT NULL REFERENCES users(id),
    last_message VARCHAR(255),
    CONSTRAINT uq_conversation_pair UNIQUE (user_one_id, user_two_id)
);

CREATE TABLE direct_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deleted BOOLEAN NOT NULL,
    edited BOOLEAN NOT NULL,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id),
    created_at TIMESTAMP(6) NOT NULL,
    sender_id BIGINT NOT NULL REFERENCES users(id),
    updated_at TIMESTAMP(6) NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE direct_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    direct_message_id BIGINT NOT NULL REFERENCES direct_messages(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    emoji VARCHAR(20) NOT NULL,
    CONSTRAINT uq_direct_reaction UNIQUE (direct_message_id, user_id, emoji)
);

CREATE TABLE direct_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direct_message_id BIGINT NOT NULL REFERENCES direct_messages(id),
    file_size BIGINT NOT NULL,
    uploaded_at TIMESTAMP(6) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL
);

CREATE TABLE conversation_read_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id),
    last_read_message_id BIGINT REFERENCES direct_messages(id),
    updated_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    CONSTRAINT uq_conversation_read UNIQUE (conversation_id, user_id)
);

CREATE TABLE mentions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    read BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    direct_message_id BIGINT REFERENCES direct_messages(id),
    mentioned_by_id BIGINT NOT NULL REFERENCES users(id),
    mentioned_user_id BIGINT NOT NULL REFERENCES users(id),
    message_id BIGINT REFERENCES messages(id),
    read_at TIMESTAMP(6)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    read BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    recipient_id BIGINT NOT NULL REFERENCES users(id),
    reference_id BIGINT NOT NULL,
    body VARCHAR(1000) NOT NULL,
    reference_type VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL CHECK (
        type IN (
            'CHANNEL_MESSAGE', 'DIRECT_MESSAGE', 'THREAD_REPLY', 'REACTION',
            'MENTION', 'WORKSPACE_INVITE', 'CHANNEL_INVITE'
        )
    )
);

CREATE TABLE workspace_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    invitee_id BIGINT NOT NULL REFERENCES users(id),
    inviter_id BIGINT NOT NULL REFERENCES users(id),
    responded_at TIMESTAMP(6),
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    status VARCHAR(255) NOT NULL CHECK (
        status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED')
    ),
    CONSTRAINT uq_workspace_invitation UNIQUE (workspace_id, invitee_id)
);

CREATE TABLE channel_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL REFERENCES channels(id),
    created_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    invitee_id BIGINT NOT NULL REFERENCES users(id),
    inviter_id BIGINT NOT NULL REFERENCES users(id),
    responded_at TIMESTAMP(6),
    status VARCHAR(255) NOT NULL CHECK (
        status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED')
    ),
    CONSTRAINT uq_channel_invitation UNIQUE (channel_id, invitee_id, status)
);

CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    token VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    token VARCHAR(255) NOT NULL UNIQUE
);

CREATE INDEX idx_messages_channel_created ON messages(channel_id, created_at DESC);
CREATE INDEX idx_messages_parent ON messages(parent_message_id);
CREATE INDEX idx_direct_messages_conversation_created
    ON direct_messages(conversation_id, created_at DESC);
CREATE INDEX idx_notifications_recipient_created
    ON notifications(recipient_id, created_at DESC);
CREATE INDEX idx_mentions_recipient ON mentions(mentioned_user_id, created_at DESC);
