ALTER TABLE users
    ADD COLUMN IF NOT EXISTS presence_preference VARCHAR(255)
    NOT NULL DEFAULT 'ONLINE';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_users_presence_preference'
    ) THEN
        ALTER TABLE users
            ADD CONSTRAINT chk_users_presence_preference CHECK (
                presence_preference IN (
                    'ONLINE', 'AWAY', 'BUSY', 'INVISIBLE', 'OFFLINE'
                )
            );
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS refresh_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked_at TIMESTAMP(6),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_refresh_sessions_user
    ON refresh_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_sessions_expires_at
    ON refresh_sessions(expires_at);
